In [41]:
n_reservoir = 3
n_inputs = 2


S = np.ones((n_reservoir,1))
S[0,0] = 1

W = np.zeros((n_reservoir,n_reservoir))
W[0,1] = 1


I = np.zeros((n_inputs,1))
I[0,0] = 1#

WInputs = np.zeros((n_reservoir,n_inputs))

In [42]:
pre = np.dot(W,S) + np.dot(WInputs, I)
pre

array([[1.],
       [0.],
       [0.]])

In [43]:
output = np.tanh(pre)

In [44]:
output

array([[0.76159416],
       [0.        ],
       [0.        ]])

In [ ]:
import networkx as nx

class SimpleESN():
    def __init__(self,n_inputs=1,n_reservoir=1):
        self.n_inputs = n_inputs
        self.n_reservoir = n_reservoir
        
        self.S = np.zeros((n_reservoir,1))

        self.W = np.zeros((n_reservoir,n_reservoir))

        self.I = np.zeros((n_inputs,1))

        self.WInputs = np.zeros((n_reservoir,n_inputs))
        
    def _update(self):
        preactivation = np.dot(self.W,self.S) + np.dot(self.WInputs, self.I)
        activation = np.tanh(preactivation)
        return activation
        

        
class GraphESN():
    def __init__(self, esn):
        self.G = nx.DiGraph()
        
        # Add nodes
        for n in np.arange(esn.S.shape[0]):
            self.G.add_node(n)

        # Add Connections:
        for n in np.arange(esn.W.shape[0]):
            for m in np.arange(esn.W.shape[1]):
                if esn.W[n,m] != 0:
                    self.G.add_edge(n,m,weight = esn.W[n,m])
                    print "%s x %s = %s" %(n,m,esn.W[n,m])
                else:
                    print "%s x %s = %s" %(n,m,esn.W[n,m])
                    
                    
                

                
                
                
                
            
x = SimpleESN(2,2)
x.W = -(np.eye(2,2)-1)

g = GraphESN(x)
nx.draw(g.G)
plt.show()

g.G.edges()
x.W

In [ ]:
x = SimpleESN(2,2)
print x.S.shape

x.W = np.ones(x.W.shape)
x.I = np.ones(x.I.shape) * 0.1
x.WInputs = np.ones(x.WInputs.shape)

s= []

for i in np.arange(100):
    x.S = x._update()
    s.append(x.S)
    
plt.plot(np.array(s).flatten())
plt.show()

In [ ]:
#x.S
x._update()

In [28]:
np.dot(x.I,x.WInputs)

array([0.2, 0.2])